# Stage-Based Training Configuration for Otitis Classifier
# Medical AI best practices: Strict data isolation across training stages

datasets:
  # Stage 1: Base Training Dataset
  ebasaran_kaggle:
    name: "Ebasaran-Kaggle"
    path: "data/raw/ebasaran-kaggale"
    processed_path: "data/processed/ebasaran-kaggale"
    format: "tiff"
    total_images: 956
    role: "base_training"
    stage: 1
    split_ratio:
      train: 0.8
      val: 0.2
    augmentation_strength: "aggressive"
    classes:
      - "Normal"      # 535 images
      - "Aom"         # 119 images  
      - "Chornic"     # 63 images
      - "Earwax"      # 140 images
      - "Foreign"     # 3 images
      - "Earventulation" # 16 images
      # TODO: Add remaining classes with counts

  # Stage 2: Fine-Tuning Dataset
  uci_kaggle:
    name: "UCI-Kaggle"
    path: "data/raw/uci-kaggle"
    processed_path: "data/processed/uci-kaggle"
    format: "jpg"
    estimated_images: 900
    role: "fine_tuning"
    stage: 2
    split_ratio:
      train: 0.9
      val: 0.1
    augmentation_strength: "conservative"
    classes:
      - "Normal"
      - "Acute Otitis Media"
      - "Cerumen Impaction"  
      - "Chronic Otitis Media"
      - "Myringosclerosis"
    # TODO: Map to unified class names

  # Stage 3: External Validation Dataset
  vanak_figshare:
    name: "VanAk-Figshare"
    path: "data/raw/vanak-figshare"
    processed_path: "data/processed/vanak-figshare"
    format: "png"
    estimated_images: 270
    role: "external_validation"
    stage: 3
    split_ratio:
      test: 1.0
    augmentation_strength: "none"
    data_isolation: "strict"  # Never used for training
    classes:
      - "Normal"
      - "AOM"
      - "CSOM" 
      - "Earwax"
      - "Miringoskleroz"
      - "OtitisEksterna"
      - "TympanostomyTubes"
    # TODO: Map to unified class names

  # Clinical Interpretability Validation
  sumotosima_github:
    name: "Sumotosima-GitHub"
    path: "data/raw/sumotosima-github"
    format: "csv"
    cases: 38
    role: "interpretability_validation"
    stage: "post_training"
    description: "Expert clinical annotations for model interpretation validation"

# Unified class mapping across datasets
unified_classes:
  num_classes: 9
  class_names:
    - "Normal_Tympanic_Membrane"
    - "Acute_Otitis_Media"
    - "Chronic_Otitis_Media"
    - "Cerumen_Impaction"
    - "Otitis_Externa"
    - "Myringosclerosis"
    - "Tympanostomy_Tubes"
    - "Foreign_Bodies"
    - "Pseudo_Membranes"

  # Clinical priority levels for loss weighting
  clinical_priority:
    "Normal_Tympanic_Membrane": "baseline"
    "Acute_Otitis_Media": "critical"
    "Chronic_Otitis_Media": "high"  
    "Cerumen_Impaction": "medium"
    "Otitis_Externa": "medium"
    "Myringosclerosis": "medium"
    "Tympanostomy_Tubes": "medium"
    "Foreign_Bodies": "critical"
    "Pseudo_Membranes": "low"

# Stage-Based Training Pipeline
training_pipeline:
  stages:
    - name: "base_training"
      dataset: "ebasaran_kaggle"
      objective: "Foundation model training with comprehensive class coverage"
      image_size: 500
      use_radimagenet: true
      
    - name: "fine_tuning"
      dataset: "uci_kaggle" 
      objective: "Domain adaptation on different institutional source"
      image_size: 500
      use_radimagenet: true
      
    - name: "external_validation"
      dataset: "vanak_figshare"
      objective: "Unbiased evaluation on completely external dataset"
      image_size: 500
      use_radimagenet: true

# Data Isolation Validation
isolation_rules:
  strict_separation: true
  contamination_detection: true
  cross_stage_validation: false
  external_test_protection: true

# Image Processing Standards
processing:
  target_resolution: 500  # Full medical image detail preservation
  format: "png"  # Lossless medical imaging
  enhancement: "clahe"  # Medical-grade contrast enhancement
  quality_threshold: 0.8